In [1]:
import re
import pandas as pd
import seaborn as sns
import numpy as np
import spacy
import unicodedata
import en_core_web_sm
import seaborn as sns
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt  
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import f1_score
from sklearn.metrics import auc
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import average_precision_score, auc, roc_curve, precision_recall_curve
from textblob import TextBlob
import random
from sklearn.metrics import accuracy_score, log_loss
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [2]:
df=pd.read_csv('C:/Users/anagha.bhople/Desktop/Sentiment Analysis/preprocess_womens_clothing_reviews.csv')

In [3]:
df.head(2)

Unnamed: 0  index                                        Review Text  \
0           0      0  Absolutely wonderful - silky and sexy and comf...   
1           1      1  Love this dress!  it's sooo pretty.  i happene...   

   Rating  Recommended IND  Positive Feedback Count  \
0       4                1                        0   
1       5                1                        4   

                            Review Text Precrocessed  Label  Label_3C  \
0  absolutely wonderful silk and sex and comfortable      1         1   
1  love this dress -PRON- is soon pretty i happen...      1         1   

                            Review Text no Stopwords  \
0          absolutely wonderful silk sex comfortable   
1  love dress soon pretty happen find store am gl...   

                                      tokenized_text  
0  ['absolutely', 'wonderful', 'silk', 'sex', 'co...  
1  ['love', 'dress', 'soon', 'pretty', 'happen', ...

In [4]:
X, y = df['Review Text Precrocessed'], df['Label']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [5]:
def tokenize(x):
    x= TextBlob(str(x)).words
    return x

In [6]:
stopwords = ['a', 'about', 'an', 'and', 'are', 'as', 'at', 'be', 'been', 'but', 'by', 'can', \
             'even', 'ever', 'for', 'from', 'get', 'had', 'has', 'have', 'he', 'her', 'hers', 'his', \
             'how', 'i', 'if', 'in', 'into', 'is', 'it', 'its', 'just', 'me', 'my', 'of', 'on', 'or', \
             'see', 'seen', 'she', 'so', 'than', 'that', 'the', 'their', 'there', 'they', 'this', \
             'to', 'was', 'we', 'were', 'what', 'when', 'which', 'who', 'will', 'with', 'you','-PRON-']

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words=stopwords, tokenizer= tokenize, ngram_range=(1, 2), max_df=0.9, min_df=3, sublinear_tf=True)

In [7]:
from sklearn.pipeline import Pipeline

In [43]:
classifier = LogisticRegression()

In [9]:
sentiment_pipeline = Pipeline([
        ('vectorizer', tfidf),
        ('classifier', classifier)
    ])

In [10]:
sentiment_pipeline.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:383: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['pron'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '


Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(max_df=0.9, min_df=3, ngram_range=(1, 2),
                                 stop_words=['a', 'about', 'an', 'and', 'are',
                                             'as', 'at', 'be', 'been', 'but',
                                             'by', 'can', 'even', 'ever', 'for',
                                             'from', 'get', 'had', 'has',
                                             'have', 'he', 'her', 'hers', 'his',
                                             'how', 'i', 'if', 'in', 'into',
                                             'is', ...],
                                 sublinear_tf=True,
                                 tokenizer=<function tokenize at 0x000002512A556040>)),
                ('classifier', LogisticRegression())])

In [11]:
y_pred = sentiment_pipeline.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [12]:
Classification_report = classification_report(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
Accuracy_score = accuracy_score(y_test, y_pred)
print('Accuracy Score: {}'.format(Accuracy_score))
F1_score = f1_score(y_test, y_pred)
print('F1 Score: {}'.format(F1_score))

[[ 729  542]
 [ 151 4239]]
              precision    recall  f1-score   support

           0       0.83      0.57      0.68      1271
           1       0.89      0.97      0.92      4390

    accuracy                           0.88      5661
   macro avg       0.86      0.77      0.80      5661
weighted avg       0.87      0.88      0.87      5661

Accuracy Score: 0.8775834658187599
F1 Score: 0.9244357212953876


In [13]:
classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="rbf", C=0.025, probability=True),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier()
    ]

for classifier in classifiers:
    pipe = Pipeline(steps=[('preprocessor', tfidf),
                      ('classifier', classifier)])
    pipe.fit(X_train, y_train)   
    print(classifier)
    print("model score: %.3f" % pipe.score(X_test, y_test))
    Classification_report = classification_report(y_test, y_pred)
    
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    Accuracy_score = accuracy_score(y_test, y_pred)
    print('Accuracy Score: {}'.format(Accuracy_score))
    F1_score = f1_score(y_test, y_pred)
    print('F1 Score: {}'.format(F1_score))


KNeighborsClassifier(n_neighbors=3)
model score: 0.822
[[ 729  542]
 [ 151 4239]]
              precision    recall  f1-score   support

           0       0.83      0.57      0.68      1271
           1       0.89      0.97      0.92      4390

    accuracy                           0.88      5661
   macro avg       0.86      0.77      0.80      5661
weighted avg       0.87      0.88      0.87      5661

Accuracy Score: 0.8775834658187599
F1 Score: 0.9244357212953876
SVC(C=0.025, probability=True)
model score: 0.775
[[ 729  542]
 [ 151 4239]]
              precision    recall  f1-score   support

           0       0.83      0.57      0.68      1271
           1       0.89      0.97      0.92      4390

    accuracy                           0.88      5661
   macro avg       0.86      0.77      0.80      5661
weighted avg       0.87      0.88      0.87      5661

Accuracy Score: 0.8775834658187599
F1 Score: 0.9244357212953876
DecisionTreeClassifier()
model score: 0.786
[[ 729  542]
 [

# Gensim Word2vec

In [14]:
import gensim
from gensim.models import Word2Vec

In [15]:
def tokenize(x):
    x= TextBlob(str(x)).words
    return x
df['Review Text w2v']=df['Review Text Precrocessed'].apply(lambda x: tokenize(x))

In [16]:
X=df['Review Text w2v']
y=df['Label']

In [17]:
w2v_Y=y
w2v_X=X
w2vX_train, w2vX_test, w2vy_train, w2vy_test = train_test_split(w2v_X,w2v_Y, test_size=.20, random_state=101)

In [18]:
X.shape

(22642,)

In [19]:
model = Word2Vec(X, size=550, window=50, min_count=30, workers=10, sg=0, iter=200)
#w2v = dict(zip(model.wv.index2word, model.wv.syn0))

In [20]:
# class MeanEmbeddingVectorizer(object):
#     def __init__(self, word2vec):
#         self.word2vec = word2vec
#         # if a text is empty we should return a vector of zeros
#         # with the same dimensionality as all the other vectors
#         self.dim = len(word2vec.itervalues().next())

#     def fit(self, X, y):
#         return self
    
#     def document_vector(doc):
#         doc = [word for word in doc if word in model.wv.vocab]
#         return np.mean(model[doc], axis=0)

#     def transform(self, X):
#         return X.apply(document_vector)

class MeanEmbeddingVectorizer(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        # if a text is empty we should return a vector of zeros
        # with the same dimensionality as all the other vectors
        

    def fit(self, X, y):
        return self

    def transform(self, X):
        
        asd= np.array([
            np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
            for words in X
        ])
        
        print(X.shape)
        print(asd.shape)
        return asd

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import ExtraTreesClassifier

etree_w2v = Pipeline([
    ("word2vec vectorizer", MeanEmbeddingVectorizer(model)),
    ('classifier', classifier)])

In [34]:
etree_w2v.fit(w2vX_train, w2vy_train)  

w2vy_pred = etree_w2v.predict(w2vX_test)

print(classifier)
print("model score: %.3f" % etree_w2v.score(w2vX_test, w2vy_test))

print(confusion_matrix(w2vy_test, w2vy_pred))
print(classification_report(w2vy_test, w2vy_pred))
Accuracy_score = accuracy_score(w2vy_test, w2vy_pred)
print('Accuracy Score: {}'.format(Accuracy_score))
F1_score = f1_score(w2vy_test, w2vy_pred)
print('F1 Score: {}'.format(F1_score))
Average_precision = average_precision_score(w2vy_test, w2vy_pred)
print('Average precision-recall score: {}'.format(Average_precision))

<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


(18113,)
(18113, 550)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


(4529,)
(4529, 550)
LogisticRegression()


<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


(4529,)
(4529, 550)
model score: 0.877
[[ 680  351]
 [ 204 3294]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71      1031
           1       0.90      0.94      0.92      3498

    accuracy                           0.88      4529
   macro avg       0.84      0.80      0.82      4529
weighted avg       0.87      0.88      0.87      4529

Accuracy Score: 0.8774563921395452
F1 Score: 0.9223015539689206
Average precision-recall score: 0.8960436276175099


In [35]:
classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="rbf", C=0.025, probability=True),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier()
    ]

for classifier in classifiers:
    pipe = Pipeline(steps=[('preprocessor', MeanEmbeddingVectorizer(model)),
                      ('classifier', classifier)])
    etree_w2v.fit(w2vX_train, w2vy_train)   
    print(classifier)
    print("model score: %.3f" % etree_w2v.score(w2vX_test, w2vy_test))
    
    print(confusion_matrix(w2vy_test, w2vy_pred))
    print(classification_report(w2vy_test, w2vy_pred))
    Accuracy_score = accuracy_score(w2vy_test, w2vy_pred)
    print('Accuracy Score: {}'.format(Accuracy_score))
    F1_score = f1_score(w2vy_test, w2vy_pred)
    print('F1 Score: {}'.format(F1_score))
    Average_precision = average_precision_score(w2vy_test, w2vy_pred)
    print('Average precision-recall score: {}'.format(Average_precision))


<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


(18113,)
(18113, 550)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


KNeighborsClassifier(n_neighbors=3)
(4529,)
(4529, 550)
model score: 0.877
[[ 680  351]
 [ 204 3294]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71      1031
           1       0.90      0.94      0.92      3498

    accuracy                           0.88      4529
   macro avg       0.84      0.80      0.82      4529
weighted avg       0.87      0.88      0.87      4529

Accuracy Score: 0.8774563921395452
F1 Score: 0.9223015539689206
Average precision-recall score: 0.8960436276175099


<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


(18113,)
(18113, 550)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


SVC(C=0.025, probability=True)
(4529,)
(4529, 550)
model score: 0.877
[[ 680  351]
 [ 204 3294]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71      1031
           1       0.90      0.94      0.92      3498

    accuracy                           0.88      4529
   macro avg       0.84      0.80      0.82      4529
weighted avg       0.87      0.88      0.87      4529

Accuracy Score: 0.8774563921395452
F1 Score: 0.9223015539689206
Average precision-recall score: 0.8960436276175099


<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


(18113,)
(18113, 550)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


DecisionTreeClassifier()
(4529,)
(4529, 550)
model score: 0.877
[[ 680  351]
 [ 204 3294]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71      1031
           1       0.90      0.94      0.92      3498

    accuracy                           0.88      4529
   macro avg       0.84      0.80      0.82      4529
weighted avg       0.87      0.88      0.87      4529

Accuracy Score: 0.8774563921395452
F1 Score: 0.9223015539689206
Average precision-recall score: 0.8960436276175099


<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


(18113,)
(18113, 550)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


RandomForestClassifier()
(4529,)
(4529, 550)
model score: 0.877
[[ 680  351]
 [ 204 3294]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71      1031
           1       0.90      0.94      0.92      3498

    accuracy                           0.88      4529
   macro avg       0.84      0.80      0.82      4529
weighted avg       0.87      0.88      0.87      4529

Accuracy Score: 0.8774563921395452
F1 Score: 0.9223015539689206
Average precision-recall score: 0.8960436276175099


<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


(18113,)
(18113, 550)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


AdaBoostClassifier()
(4529,)
(4529, 550)
model score: 0.877
[[ 680  351]
 [ 204 3294]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71      1031
           1       0.90      0.94      0.92      3498

    accuracy                           0.88      4529
   macro avg       0.84      0.80      0.82      4529
weighted avg       0.87      0.88      0.87      4529

Accuracy Score: 0.8774563921395452
F1 Score: 0.9223015539689206
Average precision-recall score: 0.8960436276175099


<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


(18113,)
(18113, 550)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)
<ipython-input-20-ceca36e667ed>:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  np.mean([self.word2vec[w] for w in words if w in self.word2vec], axis=0)


GradientBoostingClassifier()
(4529,)
(4529, 550)
model score: 0.877
[[ 680  351]
 [ 204 3294]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71      1031
           1       0.90      0.94      0.92      3498

    accuracy                           0.88      4529
   macro avg       0.84      0.80      0.82      4529
weighted avg       0.87      0.88      0.87      4529

Accuracy Score: 0.8774563921395452
F1 Score: 0.9223015539689206
Average precision-recall score: 0.8960436276175099


# Without Pipeline

In [28]:
def document_vector(doc):
    """Create document vectors by averaging word vectors. Remove out-of-vocabulary words."""
    doc = [word for word in doc if word in model.wv.vocab]
    return np.mean(model[doc], axis=0)


df['doc_vector'] = df['Review Text w2v'].apply(document_vector)
#test['doc_vector'] = df['Review Text w2v'].apply(document_vector)


<ipython-input-28-dca77d387cdc>:4: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  return np.mean(model[doc], axis=0)


In [29]:
X1 = list(df['doc_vector'])
w_Y=df['Label']
w_X=X1
wX_train, wX_test, wy_train, wy_test = train_test_split(w_X,w_Y, test_size=.20, random_state=101)

In [30]:
def LogisticRegression_binary_classification(X_train, y_train, X_test, y_test):
    logisticRegr = LogisticRegression()
    
    logisticRegr.fit(X_train, y_train)
    
    predictions = logisticRegr.predict(X_test)
    Confusion_matrix = confusion_matrix(y_test, predictions)
    Classification_report = classification_report(y_test, predictions)
    print(confusion_matrix(y_test,predictions))
    print(classification_report(y_test, predictions))
    Accuracy_score = accuracy_score(y_test, predictions)
    print('Accuracy Score: {}'.format(Accuracy_score))
    F1_score = f1_score(y_test, predictions)
    print('F1 Score: {}'.format(F1_score))
    return Confusion_matrix, Classification_report

In [31]:
LogisticRegression_binary_classification(wX_train, wy_train, wX_test, wy_test)

[[ 680  351]
 [ 204 3294]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71      1031
           1       0.90      0.94      0.92      3498

    accuracy                           0.88      4529
   macro avg       0.84      0.80      0.82      4529
weighted avg       0.87      0.88      0.87      4529

Accuracy Score: 0.8774563921395452
F1 Score: 0.9223015539689206


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


(array([[ 680,  351],
        [ 204, 3294]], dtype=int64),
 '              precision    recall  f1-score   support\n\n           0       0.77      0.66      0.71      1031\n           1       0.90      0.94      0.92      3498\n\n    accuracy                           0.88      4529\n   macro avg       0.84      0.80      0.82      4529\nweighted avg       0.87      0.88      0.87      4529\n')

# Glove with pipeline

In [458]:
X2, y2 = df['Review Text no Stopwords'], df['Label']
gX_train, gX_test, gy_train, gy_test = train_test_split(X2, y2, random_state=42)

In [459]:
%%time
glove_vectors = dict()
file = open('C:/Users/anagha.bhople/Desktop/Sentiment Analysis/GloVe Word Embedding/glove/glove.6B.100d.txt', encoding='utf-8')

for line in file:
    values = line.split()
    
    word  = values[0]
    vectors = np.asarray(values[1:])
    glove_vectors[word] = vectors
    
file.close()

In [500]:
global arr 
arr= np.zeros(100)

class glove(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        global arr 
        arr= np.zeros(100)

    def fit(self, X2, y2):
        return self
    
    def get_vec(self, X2):
        arr = np.zeros(100)
        text = str(X2).split()

        for t in text:
            #print(t)
            try:
                vec = self.word2vec.get(t).astype(float)
                arr = arr + vec
            except:
                pass
        arr = arr.reshape(1, -1)[0]
        #print(arr.shape)
        return arr/len(text)


    def transform(self, X2):
        lis=np.array(X2.apply(lambda x: self.get_vec(x)))
        #print(lis.shape)
        lis = lis.reshape(1, -1)[0]
        lis = np.concatenate(lis, axis = 0).reshape(-1, 100)
        #print(lis.shape)
        return lis
       

In [491]:
from sklearn.pipeline import Pipeline
from sklearn.pipeline import Pipeline, FeatureUnion

glo = Pipeline([
    ("word2vec vectorizer", glove(glove_vectors)),
    ('classifier', classifier)])

In [492]:
glo.fit(gX_train, gy_train)  

gy_pred = glo.predict(gX_test)

print(classifier)
print("model score: %.3f" % glo.score(gX_test, gy_test))

print(confusion_matrix(gy_test, gy_pred))
print(classification_report(gy_test, gy_pred))
Accuracy_score = accuracy_score(gy_test, gy_pred)
print('Accuracy Score: {}'.format(Accuracy_score))
F1_score = f1_score(gy_test, gy_pred)
print('F1 Score: {}'.format(F1_score))
Average_precision = average_precision_score(gy_test, gy_pred)
print('Average precision-recall score: {}'.format(Average_precision))

(16981,)
(16981, 100)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


(5661,)
(5661, 100)
LogisticRegression()
(5661,)
(5661, 100)
model score: 0.818
[[ 487  784]
 [ 248 4142]]
              precision    recall  f1-score   support

           0       0.66      0.38      0.49      1271
           1       0.84      0.94      0.89      4390

    accuracy                           0.82      5661
   macro avg       0.75      0.66      0.69      5661
weighted avg       0.80      0.82      0.80      5661

Accuracy Score: 0.8177000529941706
F1 Score: 0.8892228424216402
Average precision-recall score: 0.8371520025776354


# Hyperparameter Tuning

In [501]:
classifiers = [
    LogisticRegression(),
    RandomForestClassifier()
    ]

for classifier in classifiers:
    pipe = Pipeline(steps=[("word2vec vectorizer", glove(glove_vectors)),
                      ('classifier', classifier)])


In [508]:
from sklearn.model_selection import RandomizedSearchCV

# Create dictionary with candidate learning algorithms and their hyperparameters
search_space = [
 {"classifier": [RandomForestClassifier()],
 "classifier__max_features": [1, 2]}]

# Create grid search
randomizedsearch = RandomizedSearchCV(pipe, search_space, cv=5, verbose=0)

# Fit grid search
best_model = randomizedsearch.fit(gX_train, gy_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 2 is smaller than n_iter=10. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


In [509]:
best_model.best_estimator_.get_params()

{'memory': None,
 'steps': [('word2vec vectorizer', <__main__.glove at 0x25417455610>),
  ('classifier', RandomForestClassifier(max_features=2))],
 'verbose': False,
 'word2vec vectorizer': <__main__.glove at 0x25417455610>,
 'classifier': RandomForestClassifier(max_features=2),
 'classifier__bootstrap': True,
 'classifier__ccp_alpha': 0.0,
 'classifier__class_weight': None,
 'classifier__criterion': 'gini',
 'classifier__max_depth': None,
 'classifier__max_features': 2,
 'classifier__max_leaf_nodes': None,
 'classifier__max_samples': None,
 'classifier__min_impurity_decrease': 0.0,
 'classifier__min_impurity_split': None,
 'classifier__min_samples_leaf': 1,
 'classifier__min_samples_split': 2,
 'classifier__min_weight_fraction_leaf': 0.0,
 'classifier__n_estimators': 100,
 'classifier__n_jobs': None,
 'classifier__oob_score': False,
 'classifier__random_state': None,
 'classifier__verbose': 0,
 'classifier__warm_start': False}

In [510]:
gy_pred = best_model.predict(gX_test)

print("model score: %.3f" % best_model.score(gX_test, gy_test))

print(confusion_matrix(gy_test, gy_pred))
print(classification_report(gy_test, gy_pred))
Accuracy_score = accuracy_score(gy_test, gy_pred)
print('Accuracy Score: {}'.format(Accuracy_score))
F1_score = f1_score(gy_test, gy_pred)
print('F1 Score: {}'.format(F1_score))
Average_precision = average_precision_score(gy_test, gy_pred)
print('Average precision-recall score: {}'.format(Average_precision))

model score: 0.787
[[  96 1175]
 [  31 4359]]
              precision    recall  f1-score   support

           0       0.76      0.08      0.14      1271
           1       0.79      0.99      0.88      4390

    accuracy                           0.79      5661
   macro avg       0.77      0.53      0.51      5661
weighted avg       0.78      0.79      0.71      5661

Accuracy Score: 0.7869634340222575
F1 Score: 0.8784764207980653
Average precision-recall score: 0.7875900698301181


In [520]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV

In [526]:
pipe_LR = Pipeline(steps=[("word2vec vectorizer", glove(glove_vectors)),
                      ('clf', LogisticRegression())])

In [523]:
pipe_RF = Pipeline(steps=[("word2vec vectorizer", glove(glove_vectors)),
                      ('clf', RandomForestClassifier())])

In [527]:
pipe_SVM = Pipeline(steps=[("word2vec vectorizer", glove(glove_vectors)),
                      ('clf', svm.SVC())])

In [ ]:
# Set grid search params
param_range = [9, 10]
param_range_fl = [1.0, 0.5]

grid_params_lr = [{'clf__penalty': ['l1', 'l2'],
        'clf__C': param_range_fl,
        'clf__solver': ['liblinear']}] 


# grid_params_rf = [{'clf__criterion': ['gini', 'entropy'],
#         'clf__max_depth': param_range,
#         'clf__min_samples_split': param_range[1:]}]

grid_params_svm = [{'clf__kernel': ['linear', 'rbf'], 
        'clf__C': param_range}]

# Construct grid searches
jobs = -1

LR = GridSearchCV(estimator=pipe_LR,
            param_grid=grid_params_lr,
            scoring='accuracy',
            cv=10) 



# RF = GridSearchCV(estimator=pipe_rf,
#             param_grid=grid_params_rf,
#             scoring='accuracy',
#             cv=10, 
#             n_jobs=jobs)


SVM = GridSearchCV(estimator=pipe_SVM,
            param_grid=grid_params_svm,
            scoring='accuracy',
            cv=10,
            n_jobs=jobs)



# List of pipelines for iterating through each of them
grids = [LR,SVM]

# Creating a dict for our reference
grid_dict = {0: 'Logistic Regression', 
        1: 'Support Vector Machine'}

# Fit the grid search objects
print('Performing model optimizations...')
best_acc = 0.0
best_clf = 0
best_gs = ''
for idx, gs in enumerate(grids):
    print('\nEstimator: %s' % grid_dict[idx])
    gs.fit(gX_train, gy_train)
    print('Best params are : %s' % gs.best_params_)
    # Best training data accuracy
    print('Best training accuracy: %.3f' % gs.best_score_)
    # Predict on test data with best params
    gy_pred = gs.predict(gX_test)
    # Test data accuracy of model with best params
    print('Test set accuracy score for best params: %.3f ' % accuracy_score(gy_test, gy_pred))
    # Track best (highest test accuracy) model
    if accuracy_score(gy_test, gy_pred) > best_acc:
        best_acc = accuracy_score(gy_test, gy_pred)
        best_gs = gs
        best_clf = idx
print('\nClassifier with best test set accuracy: %s' % grid_dict[best_clf])



# Save best grid search pipeline to file
dump_file = 'best_grid_search_pipeline.pkl'
joblib.dump(best_gs, dump_file, compress=1)
print('\nSaved %s grid search pipeline to file: %s' % (grid_dict[best_clf], dump_file))

Performing model optimizations...

Estimator: Logistic Regression
